categories:
  - greetings
  - personal_info
  - common_questions
  - technology
  - jokes
  - weather

conversations:
  - - "hello"
    - "Hi there! How can I assist you today?"
  - - "hi"
    - "Hello! What can I do for you?"
  - - "how are you"
    - "I'm just a chatbot, but I'm always here to help!"
  - - "what is your name"
    - "I'm your personal AI assistant!"
  - - "who created you"
    - "I was created using Django and ChatterBot!"
  - - "tell me a joke"
    - "Why don’t skeletons fight each other? They don’t have the guts!"
  - - "what can you do"
    - "I can answer your questions, chat with you, and learn new things!"
  - - "what is python"
    - "Python is a programming language known for its simplicity and readability."
  - - "who is the president of USA"
    - "I need to be updated regularly for political data, but you can check the news!"
  - - "what is machine learning"
    - "Machine Learning is a field of AI that enables computers to learn from data without explicit programming."
  - - "what is django"
    - "Django is a high-level Python web framework that encourages rapid development."
  - - "how is the weather"
    - "I don't have live weather updates, but you can check online for real-time reports."
  - - "tell me another joke"
    - "Why was the math book sad? Because it had too many problems!"
